-- Invite codes for free first month ($9 base waived via Stripe coupon)
-- Generated by admins, redeemed during checkout

CREATE TABLE IF NOT EXISTS invite_codes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    max_uses INT NOT NULL DEFAULT 1,
    times_used INT NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    note TEXT,                          -- admin note (e.g. "YC batch", "Twitter promo")
    expires_at TIMESTAMPTZ,             -- NULL = never expires
    created_by TEXT NOT NULL DEFAULT 'admin',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Track who redeemed each code
CREATE TABLE IF NOT EXISTS invite_code_redemptions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    invite_code TEXT NOT NULL REFERENCES invite_codes(code),
    user_id UUID NOT NULL,
    redeemed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_invite_codes_code ON invite_codes(code);
CREATE INDEX idx_invite_redemptions_user ON invite_code_redemptions(user_id);
CREATE INDEX idx_invite_redemptions_code ON invite_code_redemptions(invite_code);

-- RLS
ALTER TABLE invite_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE invite_code_redemptions ENABLE ROW LEVEL SECURITY;

-- Service role can do everything
CREATE POLICY "Service role full access on invite_codes"
    ON invite_codes FOR ALL
    USING (auth.role() = 'service_role');

CREATE POLICY "Service role full access on invite_code_redemptions"
    ON invite_code_redemptions FOR ALL
    USING (auth.role() = 'service_role');

-- Users can read invite codes (for validation)
CREATE POLICY "Authenticated users can read invite codes"
    ON invite_codes FOR SELECT
    USING (auth.role() = 'authenticated');

-- Users can see their own redemptions
CREATE POLICY "Users can see own redemptions"
    ON invite_code_redemptions FOR SELECT
    USING (auth.uid() = user_id);
